apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
      - name: nest
        image: nest-app:v2
        ports:
        - containerPort: 3000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: nest-secret
              key: api_key
        
